[2025-09-21 20:07:21,264] ERROR log_exception() L875  Exception on /campaigns [POST] - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py L875 
Traceback (most recent call last):
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask_openapi3/scaffold.py", line 123, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/app.py", line 56, in create_campaign
    return CampaignInDB.model_validate(campaign), 201
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/pydantic/main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for CampaignInDB
updated_at
  Field required [type=missing, input_value=<Campaign 2: string>, input_type=Campaign]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
[2025-09-21 20:07:21,267] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:21] "[35m[1mPOST /campaigns HTTP/1.1[0m" 500 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:38,051] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:38,052] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:44,555] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:44] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:44,800] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:44] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:44,913] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:44] "[36mGET /openapi/redoc/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:45,224] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:45] "[36mGET /openapi/rapipdf/images/rapipdf.svg HTTP/1.1[0m" 304 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:45,248] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:45] "[36mGET /openapi/elements/images/elements.svg HTTP/1.1[0m" 304 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:45,249] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:45] "[36mGET /openapi/scalar/images/scalar.svg HTTP/1.1[0m" 304 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:45,261] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:45] "[36mGET /openapi/swagger/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:45,264] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:45] "[36mGET /openapi/rapidoc/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:46,581] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:46] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:46,829] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:46] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:47,033] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:47] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:47,036] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:47] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:07:47,264] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:07:47] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:08:00,848] ERROR log_exception() L875  Exception on /campaigns [POST] - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py L875 
Traceback (most recent call last):
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a CampaignInDB.
[2025-09-21 20:08:00,854] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 20:08:00] "[35m[1mPOST /campaigns HTTP/1.1[0m" 500 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 20:08:08,187] ERROR log_exception() L875  Exception on /campaigns [GET] - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py L875 
Traceback (most recent call last):
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/app.py", line 1231, in make_response
    rv = self.json.response(rv)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/json/provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/json/provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type CampaignInDB is not JSON serializable
