[2025-09-21 23:05:54,695] INFO _log() L97    * Detected change in '/home/fabio/pucpos/projeto1/rpg_app_api/app.py', reloading - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:05:56,662] INFO _log() L97    * Detected change in '/home/fabio/pucpos/projeto1/rpg_app_api/app.py', reloading - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:06:35,339] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 23:06:35] "[35m[1mOPTIONS /campaigns HTTP/1.1[0m" 500 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:06:35,354] ERROR _log() L97   Error on request:
Traceback (most recent call last):
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 974, in app
    raise err from None
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 963, in run_command
    app: WSGIApplication = info.load_app()  # pyright: ignore
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 353, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 250, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/home/fabio/pucpos/projeto1/rpg_app_api/app.py", line 12, in <module>
    from schemas.erro import ErrorSchema
  File "/home/fabio/pucpos/projeto1/rpg_app_api/schemas/__init__.py", line 8, in <module>
    from .notes import (
ImportError: cannot import name 'NoteUpdate' from 'schemas.notes' (/home/fabio/pucpos/projeto1/rpg_app_api/schemas/notes.py) - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:05:59,124] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 23:05:59] "[35m[1mOPTIONS /campaigns HTTP/1.1[0m" 500 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:05:59,128] ERROR _log() L97   Error on request:
Traceback (most recent call last):
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 974, in app
    raise err from None
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 974, in app
    raise err from None
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 963, in run_command
    app: WSGIApplication = info.load_app()  # pyright: ignore
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 353, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 250, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/home/fabio/pucpos/projeto1/rpg_app_api/app.py", line 12, in <module>
    from schemas.erro import ErrorSchema
  File "/home/fabio/pucpos/projeto1/rpg_app_api/schemas/__init__.py", line 8, in <module>
    from .notes import (
ImportError: cannot import name 'NoteUpdate' from 'schemas.notes' (/home/fabio/pucpos/projeto1/rpg_app_api/schemas/notes.py) - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:05:59,466] INFO _log() L97    * Detected change in '/home/fabio/pucpos/projeto1/rpg_app_api/app.py', reloading - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:06:29,529] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 23:06:29] "[35m[1mPOST /campaigns HTTP/1.1[0m" 500 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:06:29,558] ERROR _log() L97   Error on request:
Traceback (most recent call last):
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 974, in app
    raise err from None
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 963, in run_command
    app: WSGIApplication = info.load_app()  # pyright: ignore
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 353, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 250, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/home/fabio/pucpos/projeto1/rpg_app_api/app.py", line 12, in <module>
    from schemas.erro import ErrorSchema
  File "/home/fabio/pucpos/projeto1/rpg_app_api/schemas/__init__.py", line 8, in <module>
    from .notes import (
ImportError: cannot import name 'NoteUpdate' from 'schemas.notes' (/home/fabio/pucpos/projeto1/rpg_app_api/schemas/notes.py) - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:12:13,305] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:12:13,305] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:12:16,147] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 23:12:16] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:12:16,396] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 23:12:16] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:12:16,548] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 23:12:16] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:12:16,551] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 23:12:16] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-09-21 23:12:16,993] INFO _log() L97   127.0.0.1 - - [21/Sep/2025 23:12:16] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/home/fabio/pucpos/projeto1/rpg_app_api/venv/lib/python3.12/site-packages/werkzeug/_internal.py L97  
